### ISSUE TITLE
Support Helm images with colons

### ISSUE THREAD

**Issue by jabdoa2** [windmilleng/tilt#1059]
Tags in images (e.g. registry.tld/path/image:1) do not work in tilt. It will complain that `image registry.tld/path/image is not used in any resource`. Even if I run: docker_build("registry.tld/path/image:1", ".")`. This is a show stopper for us because we would have to change all helm charts to use it.

**Comment by nicks** [comment]
sorry you ran into this! we're working on making this better.

You can keep the show going right now by just dropping the tag. Tilt ignores the tag anyway. i.e.,

```
docker_build("registry.tld/path/image", ".")
```

@dougsparling also ran into this and has an open PR so that it doesn't fail so cryptically: https://github.com/windmilleng/tilt/pull/1047
