### ISSUE TITLE
k8s_resource for "out-of-the-box" services

### ISSUE THREAD

**Issue by nadilas** [windmilleng/tilt#1103]
Hi,

I'd like to start off my Tiltfile with a few base services which my cluster depends on, and I would like to set up port forwarding as well. So far the file is pretty simple, yet it runs into a problem.
```python

# dgraph
k8s_resource('dgraph', './dgraph/single.yaml', port_forwards=[8080, 9080, 8000, 5080, 6080])

# fusionauth
k8s_resource('fusionauth', kustomize('fusionauth-infrastructure/kubernetes'), port_forwards=[9011])

# kill-bill setup
k8s_resource('killbill', kustomize('killbill'), port_forwards=[9090, 8080, 8000, 12345])
```

The errors reported are:
```
──┤ Building: dgraph ├──────────────────────────────────────────────
Build Failed: ImageBuildAndDeployer does not support these specs

──┤ Building: fusionauth ├──────────────────────────────────────────────
Build Failed: ImageBuildAndDeployer does not support these specs

──┤ Building: killbill ├──────────────────────────────────────────────
Build Failed: ImageBuildAndDeployer does not support these specs
```

I also tried running the installs at the beginning via `k8s_yaml` but then the k8s_resource doesn't find it:
```
k8s_yaml('./dgraph/single.yaml')
k8s_resource('dgraph', port_forwards=[8080, 9080, 8000, 5080, 6080])

--- results in:
Tiltfile error:
resource "dgraph": no matching resource
```

Can such "ready-made" services be deployed before my development packages are built?

**Comment by nicks** [comment]
Hi @nadilas! Sorry you ran into trouble with this. I think there's a bug right now that if you have a k8s_resource without a Dockerfile attached, everything gets confused. @maiamcc do you know if there was already a bug filed about this?

also, any chance that the project with dgraph/single.yaml is an open-source project? It would be helpful to test the fix against a real project so that we know we fixed it.

**Comment by maiamcc** [comment]
Nope, no ticket open as far as I know -- will file one now! Thanks for the report @nadilas !

**Comment by nadilas** [comment]
@maiamcc no problem 🙃
@nicks the source code is actually available: https://github.com/dgraph-io/dgraph

Does that help?

**Comment by maiamcc** [comment]
Hi @nadilas,

sorry for the radio silence, but wanted to let you know that we've got a PR in flight for this (#1156), and i'll check it against your source code tomorrow morning!

**Comment by maiamcc** [comment]
Ah so, the good news is, you CAN declare a `k8s_resource` with only yaml and portforwards and without an associated `docker_build`, and it'll spin up:
![screen shot 2019-02-12 at 6 43 32 pm](https://user-images.githubusercontent.com/6332648/52675854-23dc8d80-2ef6-11e9-9f0a-665958aea297.png)

The bad news is that Tilt currently only supports portforwarding for a single container: right now it's picking up `ratel` because it's the first, and all of the local ports you specified are connecting to `ratel:8000`.

Is this functionality still blocking you?

I assume in your original Tiltfile, with `port_forwards=[8080, 9080, 8000, 5080, 6080]` you intended the first container port (ratel) to forward to 8080, the next two (zero) to forward to 9080 and 8000 respectively, etc.?

**Comment by maiamcc** [comment]
Hi @nadilas,

Just following up -- I assume the above is still blocking you? Or have you found a workaround?

**Comment by nadilas** [comment]
Hi @maiamcc,
sorry for going dark. So that is actually good news. Do you have a Tiltfile as an example? Or is it just a one liner:
k8s_resource(‘name’, ‘yaml’, port_forwards=[8080]) after a version update?

The yaml file for dgraph is from there doc, maybe the containers can be decoupled, I have to look into it. But yes, your assumption is correct I wanted the port delegation to happen in that order yes.

**Comment by maiamcc** [comment]
Yeah, that one-liner should work! [Check out this branch](https://github.com/windmilleng/servantes/tree/out-of-the-box) for a tiny example!

"Support pods running multiple containers" is on our radar as a future feature, but for now, let me know if you can split out the containers/get this code running, and when you do I'll close the issue.

**Comment by maiamcc** [comment]
@nadilas I'm gonna go ahead and close this issue, but let me know if you run into any trouble getting this running and I can help you debug!

**Comment by nadilas** [comment]
@maiamcc thanks a lot! I’ll get back to you, should anything unforeseen happen :-)

**Comment by maiamcc** [comment]
FYI @nadilas we're slowly making progress on this -- still can't port-forward multiple containers, but you can now at least get logs from them! 😅
