### ISSUE TITLE
warnings and errors without any clarifying info

### ISSUE THREAD

**Issue by nicks** [windmilleng/tilt#1713]
We received this screenshot in the Tilt channel in k8s slack:

<img width="1676" alt="Screen Shot 2019-06-05 at 2 40 56 PM" src="https://user-images.githubusercontent.com/278641/58994003-27559680-87bd-11e9-9ed5-66146ced9916.png">

<img width="1679" alt="Screen Shot 2019-06-05 at 2 33 41 PM" src="https://user-images.githubusercontent.com/278641/58994071-54a24480-87bd-11e9-9b57-bc1b9e54e8ac.png">

There are a bunch of independent problems here, but the obvious ones that pop out at me:
- the resource names are overflowing the sidebar
- there's an error, but no actual info on what the error is
- there's a warning, but no actual info on what the warning is
- not clear what the relationship is between the Alert and the error/warning

**Comment by nicks** [comment]
(trying to come up with repro cases for this, might need to be independent bugs)

**Comment by nicks** [comment]
I think one of these pods does a `wget` and then exits immediately. And we don't really surface the pod termination state in the UI

**Comment by nicks** [comment]
an easy way to repro this is to change the docker_build in https://github.com/windmilleng/tilt-helm-demo to use an image name that doesn't exist

**Comment by nicks** [comment]
(i think you can find the actual warning in the ALL/logs pane. we're definitely not surfacing it correctly)

**Comment by nicks** [comment]
ya, it looks like the warning indicator in the sidebar got removed here:
https://github.com/windmilleng/tilt/commit/67898e18d4143b384ff8f5e604b8515746cdc114#diff-0daacb7ac4bda035d3d7aaf9503b63c9R56
it looks like we tried to change it to something else, but made a mistake?

**Comment by jazzdan** [comment]
<img width="356" alt="Screen Shot 2019-06-06 at 12 20 03 PM" src="https://user-images.githubusercontent.com/452453/59049197-76e7a100-8855-11e9-9d28-ca49921c1377.png">

It _does_ add this yellow indicator to the resource. I'm not super familiar with the css here, was this an intentional change @yuindustries?

**Comment by nicks** [comment]
That's way too subtle. Neither of us (me or the user) even noticed that in the initial screenshot, even though it's a critical problem that would have helped them identify the issue.

**Comment by yuindustries** [comment]
Yes, I intentionally changed the warning indicator from the prior icon (:warning:), which used to be to the right of the resource name. Since we added the "alert count" badge, the space to the right of the resource name was getting crowded. 

I hoped the bar would read as "something is wrong/different about this resource", and that some would pick up that the yellow color matches the color of the warning icon in the footer bar. But I see your point that it was too subtle to pick up on the issue in the repro case above.

I agree that the warning indicator should be more obvious, and more related to how we notify users about alerts.
