### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by dotellie** [windmilleng/tilt#1753]
This is probably more of a question but I'm seeing some pretty extreme memory usage on my system with the `tilt` coming in at about 3.5GB of consumed RAM. Is this normal and what could it possibly be due to? My Tiltfile deploys my Helm app (with `helm template`) which only has two services where one of them is a custom Docker build and the other is Redis.

**Comment by dotellie** [comment]
I noticed that the problem seems to have been that my docker build context included my `target` folder (Rust project) which tilt kept in memory for some reason. That seems like a bug to me but I'm not quite sure :sweat_smile:

**Comment by landism** [comment]
Nope, you're right. Tilt shouldn't be using 3.5GB of ram. We'll have a release out later today that will allow you to grab a heap dump and let us see more clearly what's causing the problem.

Thanks for the report!

**Comment by landism** [comment]
Sorry for the delay on this! We've just released Tilt 0.9.0. As of this version, you can hit ctrl+O in the terminal UI to save a heap dump.

Once you've done that:
1. send us the dump directly (it might be ~3.5GB, so this might not be super convenient for you)
2. run [pprof](https://github.com/google/pprof) to analyze it and send us the analysis (`go tool pprof tilt.heap_profile` and then `dot > heap`) (this also might not be convenient, especially if you don't already have go installed).

If you could do one of these, it'd make it much easier for us to understand why Tilt is misbehaving for you, and more likely that whatever fix we implement is actually fixing your problem rather than an adjacent problem.

If it's a hassle for you, that's totally understandable, and we'll look into other ways to diagnose this.

If you have any questions, feel free to ask here or in #tilt on the K8S Slack.

**Comment by dotellie** [comment]
So I did both and, surprisingly, while gnome system monitor still reported insane memory usage from tilt (now up to about >5GB), the heapfile only ended up at a few kilobytes. Both files you requested are linked to below but I suppose those might not be of much help since they don't correspond with what the rest of the system says.

https://drive.google.com/open?id=1hyE5YXVlRxeLOMhtPU5fJT2EOCckPZlU
https://drive.google.com/open?id=1OCWqMOO9tWbuNwwFPRaJdbelyc7LRltZ

(btw, I'm on the Slack channel you mentioned. Feel free to ping me if you want to debug it in realtime @Ellie)

**Comment by landism** [comment]
I haven't gotten to a diagnosis yet, but...

Silly me. This is pretty trivial to repro:

`dd if=/dev/zero of=file.txt count=1024 bs=1048576` to create a 1gb file in a docker build context
`tilt up`

per `top`, tilt now uses ~2gb of memory
