### ISSUE TITLE
Resource stuck in pending

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#1803]
It seems like there are certain situations where resources get stuck in the pending state, even though `kubectl` reports that they are running.

Specifically we've seen this happen with a StatefulSet that has a liveness and readiness probe, but in my testing I can't reproduce it with those things so those may be red herrings.

I have some logs and YAML that go along with this report, but can't make them public.

_via @camilosantana in #tilt_

**Comment by jazzdan** [comment]
@camilosantana I'm curious if this still repros for you on [v0.9.3](https://github.com/windmilleng/tilt/releases/tag/v0.9.3). We [changed some of the behavior](https://github.com/windmilleng/tilt/commit/a15aef07a4ba97e111081480490548a1bf7b2bfa) around Pod errors that was causing empty errors in other circumstances.

If not can you send me the output of http://localhost:10350/api/view ? I'm specifically looking for:
1) What the resource in question's `CurrentBuild` value is
2) and the `PendingBuildSince` value
3) and the `RuntimeStatus` value

Thanks!

For others, I tried reproducing with:
1) Stateful set
2) Liveness probe that fails
3) Liveness probe that succeeds
4) Readiness probe that fails
5) Readiness probe that succeeds

But no luck

**Comment by maiamcc** [comment]
Hi @camilosantana -- going through some old bug reports, wondering if you're still running into this problem on the latest version of Tilt, and if so, if you could send us some more detailed repro steps. Thanks!

**Comment by camilosantana** [comment]
i got pulled away into another project but will circle back on this in the
next few weeks. i say close this out as it's gone stale. if i run into
issues with the app chart again, i'll resubmit bug and reference this
legacy ticket. thanks.

*Camilo Santana*
Sr. Site Reliability Engineer
+1 805-329-5143 <+1+805-329-5143>  |  camilo.santana@procore.com  |
procore.com <http://www.procore.com>

*Network. Learn. Innovate.* Register now for Groundbreak 2019.
<https://www.eiseverywhere.com/ereg/index.php?eventid=375957>

[image: Procore]

LinkedIn <https://www.linkedin.com/company/procore-technologies>  |
Facebook <https://www.facebook.com/procore.tech>  |  Instagram
<https://www.instagram.com/procoretech>  |  Twitter
<https://www.twitter.com/procoretech>  |  YouTube
<https://www.youtube.com/user/ProcoreVideo>

This email is intended only for the person(s) named in the message header
and, unless otherwise indicated, contains confidential and/or privileged
information. If you have received this message in error, please notify the
sender of the error and delete the message.

**Comment by camilosantana** [comment]
also best to hit me up via slack. email is flooded. i rarely check. i only
saw this as i was updating my filters.

i tend to delete messages `-*@procore.com`

*Camilo Santana*
Sr. Site Reliability Engineer
+1 805-329-5143 <+1+805-329-5143>  |  camilo.santana@procore.com  |
procore.com <http://www.procore.com>

*Network. Learn. Innovate.* Register now for Groundbreak 2019.
<https://www.eiseverywhere.com/ereg/index.php?eventid=375957>

[image: Procore]

LinkedIn <https://www.linkedin.com/company/procore-technologies>  |
Facebook <https://www.facebook.com/procore.tech>  |  Instagram
<https://www.instagram.com/procoretech>  |  Twitter
<https://www.twitter.com/procoretech>  |  YouTube
<https://www.youtube.com/user/ProcoreVideo>

This email is intended only for the person(s) named in the message header
and, unless otherwise indicated, contains confidential and/or privileged
information. If you have received this message in error, please notify the
sender of the error and delete the message.

**Comment by maiamcc** [comment]
Great, will do :) thanks!
