### ISSUE TITLE
Feature request: ability to dismiss alerts

### ISSUE THREAD

**Issue by epotex** [windmilleng/tilt#1850]
Since right now we have no way to control the order of the containers, We get alerts from applications that wait for DB  to start - when the DB start all is working but the alert is still there

will it be possible to add a feature that will allow users in the web UI to dismiss alerts?

**Comment by nicks** [comment]
Oooh, we've talked about this a bunch. It's a pretty common use-case (see https://github.com/windmilleng/tilt/issues/1846 for example).

The thing we get stuck on is how persistent we should be about the dismissal. If I dismiss the alert once, and the same error happens again, should the error come back? Or should it be snoozed for N minutes? How smart do we need to be about determining it's the "same" error? And is there a way to snooze it in the Tiltfile so that everyone on your team knows not to worry about it?

But maybe we're overthinking it and there's something simple we can do that works for most cases.

**Comment by drubin** [comment]
The problem right now that I can see is you use the cluster state as the source of truth for alerts, This coupled with the "restarted" flag makes it impossible.
 
I had two ideas.

1) Store an  immutable event log. This way when you dismiss the alerts you dismiss them from a point in time and all future events (i.e increase in restart would create another event)

2) You base your healthy state from the k8s readiness/liveness checks which were added in https://github.com/windmilleng/tilt/commit/ad34add39b7d6d9c50605b4b7529e2e6f0ff2f7f 

If your application is currently healthy the alert could automatically be dismissed. 

The issue here is that in a distributed system these types of dependancies are normal and I don't believe you should solve this by trying to hide this race condition. Docker compose and Garden try solve this with "depends on" but the issue with this approach is they only "hide" the explicitly race condition and allow developers to ignore this. i.e avoiding proper health checks and error handling. 

just my 2 cents.

**Comment by drubin** [comment]
btw we are hacking this state by deleting the pods manually(via a script) that have restarts so we can then easily see if a restart even happens later. 

This is horrid but its the only way the tilt dashboard is useful as part of a normal distributed startup flow with an application with liveness/readiness checks

**Comment by nicks** [comment]
ugh, sorry to hear that, let's see if we can do something quick just to solve the "reset restarts" case

**Comment by nicks** [comment]
We added a button to dismiss restart alerts once the pod is running; we'll see how that works.
