### ISSUE TITLE
Resource status should reflect k8s readiness checks

### ISSUE THREAD

**Issue by maiamcc** [windmilleng/tilt#1952]
From amerryman:
> we implement readiness checks for our deployments within k8s. Is it possible to surface that to the tilt UI for each resource?
> Right now we have a readiness check for our node services when they are listening on port 443, but it would be cool if it would not turn “Green” until that readiness check passed. Typically I just use `kubectl get pods` and look at the `READY` column to determine when I can actually hit the node service.

**Comment by nicks** [comment]
I played around with this a little bit in the tilt.build health check and came up with some repro steps:
1) change healthcheck.sh to probe port 4001 (instead of port 4000)
https://github.com/windmilleng/tilt.build/blob/master/healthcheck.sh
2) Run `tilt up`

Expected Result:
Services should express somehow that they're not ready yet

Actual Result:
Services are green

On the plus side, we now show events when the readiness checks fail, which is nice :clap:

**Comment by nicks** [comment]
fixed by https://github.com/windmilleng/tilt/pull/2166
