### ISSUE TITLE
Improve error message for getDigestFromBuildOutput

### ISSUE THREAD

**Issue by dbentley** [windmilleng/tilt#1967]
`ERROR: getDigestFromBuildOutput: Could not find image digest in docker output` is not useful.

In this case, we should print more of the build output so the user can include that, or even have a chance. (in this case, it looks like it was related to exhausting space on docker VM)

**Comment by maiamcc** [comment]
From Nick:
> it's not even clear to me that it's buildkit related. it really needs repro steps

**Comment by nicks** [comment]
coincidentally, someone else exhausted their space in the docker VM yesterday in the #tilt channel and the error reported as 

```
ERROR: ImageBuild: failed to create temp dir: mkdir /var/lib/docker/tmp/buildkit-mount737751980: no space left on device
```

**Comment by jazzdan** [comment]
@chuckha just ran in to the error message and it was similarly hard to debug in snapshots.

https://alerts.tilt.dev/snapshot/AeKRrNULf1HhuihId34=

**Comment by nicks** [comment]
OK, I was able to get a repro case for this.

1) Reset D4M with the smallest possible disk space
2) enter the VM with the command 
docker run -it --privileged --pid=host debian nsenter -t 1 -m -u -n -i sh
3) create files under /var/lib until you run out of disk space
dd if=/dev/zero of=/var/lib/file.txt count=300000 bs=1024
4) On the host machine repo, create some large 100MB file in the docker context
5) Run `tilt up`

Often I needed to play around a bit to get just the right amount of disk space so that I got the errors reliably without crashing the kubernetes api server.

One thing that I found helped is to create a large file (O(many GB)) and a small file (O(a few hundred MB)), then delete the small file when i needed to reset kubernetes (rather than resetting the whole VM)

There's no actual error message coming from Docker. The response Reader is empty. It looks like it's failing while trying to process the tarball. It tries to stream the tarball to disk somewhere, fails, and just falls over without sending an intelligible error.

**Comment by nicks** [comment]
OK, this is definitely a docker bug. Here's a repro case outside of Tilt:

1) Create a large tarball suitable as a docker context, > 100MB
2) enter the VM with the command
docker run -it --privileged --pid=host debian nsenter -t 1 -m -u -n -i sh
3) create files under /var/lib until you run out of disk space
dd if=/dev/zero of=/var/lib/file.txt count=300000 bs=1024
4) Run
```
DOCKER_BUILDKIT=1 docker build - < archive.tar
```

Expected result:
Docker should fail with an error message

Actual result:
Docker hangs indefinitely with no reasonable error message. Note that this works correctly with the old build engine:

```
$  docker build - < ../archive.tar 
Error response from daemon: mkdir /var/lib/docker/tmp/docker-builder312255349: no space left on device
```

Next steps:
- File this upstream against buildkit
- Try to detect this case in Tilt, and fallback to the legacy build engine

**Comment by nicks** [comment]
filed upstream as https://github.com/moby/buildkit/issues/1138

**Comment by Arvinderpal** [comment]
I'm also getting the `Error: notify.Add("/home/awander/go/src/github.com/chuckha/capi-dev/cluster-api"): watcher.Add("/home/awander/go/src/github.com/chuckha/capi-dev/cluster-api/cmd"): no space left on device`
I'm using @chuckha repo as well. 
I'm on Ubuntu 18.04 and have over 300GB free disk space. The error occurs after about 5-6 retries of the `tilt up` command. I tried most of the suggestions here: https://forums.docker.com/t/docker-no-space-left-on-device/69205
The only fix I have is to restart my machine :(

**Comment by chuckha** [comment]
@Arvinderpal have you tried deleting docker images/running pods (with -v) and pruning the docker system?

**Comment by jazzdan** [comment]
@Arvinderpal I think that's a different problem. I created issue #2079 for it.

**Comment by jazzdan** [comment]
@Arvinderpal can you paste the output of this command?

```
$ cat /etc/sysctl.conf | grep "fs.inotify"
```

**Comment by Arvinderpal** [comment]
@chuckha I will try it next time it happens. 
@jazzdan I will share the output once I see the problem again.

**Comment by nicks** [comment]
The upstream Docker bug is fixed, but won't be out until the next Docker release. I have some ideas on how to detect this is happening. 

Ya, the watcher error is unrelated, let's move discussion on that over to the other issue.

**Comment by nicks** [comment]
added a better error message for this
