### ISSUE TITLE
Show output for `docker push`

### ISSUE THREAD

**Issue by maiamcc** [windmilleng/tilt#1983]
When `docker push` is taking a really long time, it would be useful to be able to watch it's progress to know that stuff is actually happening.

When running `docker push` in terminal, you see output like:

```
if i copy the push command into my terminal i can see the progress, e.g.:
The push refers to repository [gcr.io/cn-reg/my-proj/my-app]
3138c02b014b: Pushing [===>                                               ]   85.5MB/1.169GB
69f5f2b99c1c: Pushing [========>                                          ]    147MB/861.2MB
d3c5265d0b51: Layer already exists
f3942473f472: Layer already exists
85d899103a5d: Layer already exists
0fc645cac9be: Layer already exists
...
```

Would be useful to show this (or similar) in Tilt.

(Requested by Michael Hatch in #tilt)

**Comment by hausdorff** [comment]
@maiamcc Since I think you will know what I mean by this, I'll say it to you: it would be nice to have Zulip-like "channels" for output like this that is normally very noisy, so that you can drill in/out as necessary. So, click `#docker`, which focuses output on the output for the Docker, and so on.

**Comment by maiamcc** [comment]
Hmm interesting!
