### ISSUE TITLE
Structured logs

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#2091]
It would be great to have more structured logs. This would enable us to do things like:

* Filter out pod logs, build logs, logs from certain containers, etc.
* Distinguish errors from warnings

**Comment by kavirajk** [comment]
Big +1

Single most painful thing currently for me is watch live_update happening to my pods. Its spitting out both old running pods logs and live_update build logs in the same stream. 

Even able to separate it would be big win.! as a first step!

**Comment by tmc** [comment]
I mentioned this in Slack but currently build and pod logs are interspersed -- a slow build happening during noisy logs gets lost in the web ui.

**Comment by landism** [comment]
I think the title "structured logs" is pretty big and vague and could solve a lot of important problems.

I also think that the majority of feedback we've had related to this hasn't needed changes to the existing log structure to address. We already store build logs separately from runtime logs internally, and could "just" provide a mechanism in the web UI to display the runtime or build logs by themselves (the TUI already does this, but it's of limited use due to the lack of scrollback).

Maybe there's a better solution to this that would benefit from additional log structuring? But I think this gets us 90% of the way there for less than 10% of the cost.

**Comment by nicks** [comment]
Ya, a lot of the things originally captured by this ticket are done - Tilt currently stores logs internally in different forms, and has special UI affordances for warnings vs errors vs live_updates.

I filed a separate issue for the build-and-pod log interspersing: https://github.com/windmilleng/tilt/issues/2947
