### ISSUE TITLE
[ BUGish ] Port-forward breaks, doesn't come back

### ISSUE THREAD

**Issue by Typositoire** [windmilleng/tilt#2099]
Been playing with Tilt today and I realized one thing. The port forward sometimes disappear and when this happens, there's no way to get it back other than `CTRL-C` and `tilt up`, is there anyway to have a keepalive running ?

Running tilt locally to our Kubernetes cluster in AWS.

**Comment by Typositoire** [comment]
It happens after 10 minutes. Port-forward dies.

**Comment by landism** [comment]
Thanks for the report!

Some questions, if you don't mind:

1. Is any message logged by Tilt when the port-forward stops working?
2. Can you try reproing with --debug and seeing if any more information is logged?
3. When the port forward stops working, what behavior do you observe when you try to use it? connection refused? connection timeout?

**Comment by nicks** [comment]
i think i understand the bug here. it's an issue with how we're handling the error from the portforwarding code

tbh i'm trying to figure out if it makes more sense to fork client-go's port-forwarder. it has like 4 different ways of handling error output, and none of them make much sense in a client library
