### ISSUE TITLE
Run a subset of services

### ISSUE THREAD

**Issue by tmc** [windmilleng/tilt#2172]
As the nubmer of services grows there may be use cases where only a subset of services should be brought up. It's not clear immediately how to do this in tilt.

**Comment by landism** [comment]
Yeah, we should make this more evident.

There are currently two main options:
1. Run `tilt up <service1> [<service2>] [...]`, which will run your tiltfile and then only deal with the services named on the command line. This is simple to use, but you can't change the service list without restarting Tilt, and it's not as convenient if you have a lot of services and want to have convenient ways to group them.
2. With the `read_json` Tiltfile builtin, e.g.:
```
svcgroup1():
  docker_build(...) // service A
  k8s_yaml(...) // service A

svcgroup2():
  docker_build(...) // service B 
  k8s_yaml(...) // service B
  docker_build(...) // service C
  k8s_yaml(...) // service C

service_groups = {
  'svcgroup1': svcgroup1,
  'svcgroup2': svcgroup2
}

# default value = all services
selected_services = read_yaml('tilt_services.yaml', {}).get('services', services.keys())

for name in selected_services:
  services[name]()
```

and then in tilt_services.yaml put, e.g.:
```
services:
  - svcgroup1
  - svcgroup2
```

From there, you can comment/uncomment entries in the yaml to enable/disable them in tilt.
Some customers prefer adding the yaml file to .gitignore so they don't have to worry about committing those changes.

The example above probably has room for improvement, and maybe you just wanna go with `tilt up svc1 svc2 svc3 ...` anyway.

I'll leave this ticket open since we should have proper docs for this.

**Comment by tmc** [comment]
Is it possible to use target a subset of services that are read in from a docker_compose()?

**Comment by maiamcc** [comment]
hi @tmc -- not sure I understand your specific use case, can you give me an example?

**Comment by maiamcc** [comment]
Two things that may be relevant:
1. tilt DOES support using docker compose directly, if you want Tilt's UI and responsiveness with your existing docker compose file: https://docs.tilt.dev/docker_compose.html
2. your `docker-compose.yml` is a yaml file that you can read in as a dict with the [`read_yaml()`](https://docs.tilt.dev/api.html#api.read_yaml) builtin -- you can then get the service names out of that dictionary and use them to do what matt did in his example above (i.e. only call set-up functions for those specific services)

**Comment by tmc** [comment]
Given
```
docker_compose([
    "./docker-compose.yml",
    "./other-config.yaml"
])
```
can I write something akin to `svcgroup1` above but have that group select a subset of compose-defined services?

At the end of the day I'd like to have closest to `tilt up svcgroup1` or `tilt up svcgroup1` without touching files on disk.

**Comment by maiamcc** [comment]
ah i see. Unfortunately no :( 

if `tilt up svc1 svc2 svc3` is too much of a pain, you might try:
```
export SVC_GRP_1='svc1 svc2 svc3' # in .bashrc or similar
tilt up $SVC_GRP_1
```

**Comment by landism** [comment]
We've added some new Tiltfile builtins to support this: https://docs.tilt.dev/tiltfile_config.html
