### ISSUE TITLE
tilt doesn't work if the docker server isn't running

### ISSUE THREAD

**Issue by nicks** [windmilleng/tilt#2180]
from the K8s tilt channel:

> I'm trying to use minikube on mac as my k8s cluster.  When I run tilt up, I get the following error
Error: NewDockerVersion: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

confirmed that it works on linux but fails on macos, so not sure what's going on

**Comment by landism** [comment]
The error is coming from [NewDockerClient](https://github.com/windmilleng/tilt/blob/5e29b5101a86fdda88f5f1dc8d528eb71da8a820/internal/docker/client.go#L127) via [ProvideLocalCli](https://github.com/windmilleng/tilt/blob/8c7200765a66752c8ccc602183422ffc9e76c9ca/internal/docker/clients.go#L21)

I'm not familiar with this code and am not sure of its purpose, but AIUI, we instantiate both a LocalClient and a ClusterClient on startup, and then combine them into a SwitchClient that picks whether to use LocalClient or ClusterClient based on whether we're the orchestrator is k8s.

In the case of minikube, we don't actually *use* the LocalClient, but we instantiate it anyway. Since there is no local docker daemon running, that errors, and fatally.

Two options that come to mind:
* give the switch client cluster/local factories and don't create the client until after the switch has determined which one it wants
* change ProvideLocalCli to, on error, return an exploding client instead of erroring immediately.

> confirmed that it works on linux but fails on macos, so not sure what's going on

Does it work on linux if you stop your local docker daemon? If my understanding is correct, this is not a macos vs linux issue, but a "is there a local docker daemon running or not" issue.

**Comment by nicks** [comment]
oh, wait, i'm confused. so it works ok on MacOS if your local docker client is running?

**Comment by landism** [comment]
If I start docker for desktop, then I can run Tilt.
If I stop docker for desktop, then I get the error in this issue.
If I stop docker for desktop, and run `eval $(minikube docker-env)`, then I can run Tilt.

**Comment by nicks** [comment]
OK, so there's a couple separate requirements that are conflicting in a weird way:
1) Sometimes Docker gets hosed for some reason. Users really wanted us to do a Docker healthcheck on startup, so that Tilt wouldn't just hang.
2) Tilt doesn't know which Docker client you want to use (the docker-compose client or the k8s client) until after we've executed the Tiltfile

I don't really want to delay the healthcheck until after Tiltfile loads (since this could take a long time).

hmmm...

**Comment by nicks** [comment]
fixed in #2203
