### ISSUE TITLE
Improve trigger_mode=TRIGGER_MODE_MANUAL

### ISSUE THREAD

**Issue by kvokka** [windmilleng/tilt#2211]
## Feature request

Now

```
k8s_resource('snack, trigger_mode=TRIGGER_MODE_MANUAL)
```

does not allow to restart the service, even when I have this button in the interface. But why not just re-issue the pod on the button press? It looks like native behaviour.

**Comment by nicks** [comment]
Thanks! Can you share a bit more detail on what you want to restart the pod? Like did it have a temporary error that you want to retry? Or did it start too early before another service was up? Or something else?

We've had similar "restart a thing" requests a few times, and it's been surprisingly tough because different use-cases need slightly different semantics (see https://github.com/windmilleng/tilt/issues/1928 and https://github.com/windmilleng/tilt/issues/2068)

cc @hyu who has been collecting examples of use-cases

**Comment by kvokka** [comment]
Just look at the interface:

![Screenshot 2019-09-18 at 16 27 12](https://user-images.githubusercontent.com/15954013/65162472-34775800-da31-11e9-9be4-e215d6335270.png)

The first intent after this setup was to click on it. And nothing happens :)

And in the dev process there are the cases when you need to restart only 1 service, which is on hot-reload by default with out container rebuilding (for languages like Python or Ruby or NodeJS, etc). You are do not always use livenessProbe for the development,  so now it may require too much hassle, while interfase is done already.

**Comment by maiamcc** [comment]
That all makes sense! And it seems like you have two different threads here:
1. you want the ability to force-restart your service (see #1012, #1928, #2068)
2. the existing UI is confusing because it looks as if you _can_ force-restart your service, but you can't.

**Comment by sssilver** [comment]
I second this ticket. I have specified one of our services as "manual reload", since it would be non-trivial for it to detect when it needs to be automatically reloaded. Sure enough, the UI shows (what looks like) a reload button:

![image](https://user-images.githubusercontent.com/619878/66243301-be7a1e80-e6c9-11e9-9b5c-d197347fc1a2.png)

However, nothing happens when it's clicked. How's the manual restart supposed to be triggered then?

**Comment by maiamcc** [comment]
@sssilver yeah that's a very fair point -- the idea behind manual trigger as it currently stands is that Tilt detects file changes that correspond to your service, but doesn't DO anything with them until you click "go". There's still no way to just trigger a build unless one of the associated files has changed. I totally agree that a. this should be a feature, and that b. the UI here is misleading.

**Comment by maiamcc** [comment]
Hey folks, exciting news! We've just launched a ["Force Update" feature](https://blog.tilt.dev/2019/11/14/force-update.html)! Take a look at our feature announcement and let us know if this meets your needs :)

**Comment by kvokka** [comment]
Thank you, @maiamcc ! You r awesome!
