### ISSUE TITLE
docker_build( dockerfile= ) treats tilde (~) as a relative path.

### ISSUE THREAD

**Issue by rally25rs** [windmilleng/tilt#2423]
If you do:

```
docker_build('whatever-name', '.', dockerfile='~/Projects/whatever/Dockerfile')
```

it will treat that as a relative path and give the error

```
Error: error reading dockerfile: open /Users/whoever/path_to_wherever_tilt_was_run/~/Projects/wherever/Dockerfile: no such file or
directory
```

It's be nice if a leading `~` worked the same as a leading `/` and treated it as an absolute path.

**Comment by maiamcc** [comment]
Ooh, this is an interesting one! So we're reluctant to support `~` in paths because it opens the door to Tilt configurations that are more dependent on the individual user's filesystem setup and aren't easily encapsulated in a repo. (I.e. if you're using `~` in your Tiltfile, it's likely to lead to a Tiltfile that would be difficult for someone else to run.) Can you talk a little more about your setup/directory structure why you want to be able to use `~` in your Tiltfile?

More practically speaking: you can around `~` support by using [`os.environ`](https://docs.tilt.dev/api_os.html) to get the value of `$HOME`. (Also, we should have clearer messaging around the fact that we don't support `~/...`, I'll toss that in soon.)

**Comment by rally25rs** [comment]
> Can you talk a little more about your setup/directory structure why you want to be able to use ~ in your Tiltfile?

Certainly! We're moving from a dev environment where we primarily used Vagrant to spin up a VM with everything needed for a project, and deployed to AWS EC2, to one of docker images and k8s.

Our typical workflow with Vagrant was that we would have our VMs mount a `~/Projects` directory back to the host. Most people checkout all their github repos under `~/Projects`.

When I'm building up a k8s cluster for development, our Dockerfiles tend to be in those locations still

```
~/Projects
  +- management_api/Dockerfile
  +- management_ui/Dockerfile
  ...etc
```

In my tiltfile, I left a variable at the top that a dev could change to wherever their project dir was
```
# Customize these variables so setup what you want to work on
env = 'dev'
projectsPath = '~/Projects'

...
# build api
projDir = '{}/management_api/'.format(projectsPath)
docker_build('api', projDir, dockerfile='{}/Dockerfile'.format(projDir))

# build ui
projDir = '{}/management_ui/'.format(projectsPath)
docker_build('ui', projDir, dockerfile='{}/Dockerfile'.format(projDir))
```

More simply; my main projects that are to be deployed aren't in a monorepo structure; aren't in subdirectories of the Tiltfile.
I could probably assume that they are rooted from `'../` of the Tiltfile, since most people are going to `git clone` all the projects that they need to work on into the same directory... that might be a better default value for now.

**Comment by maiamcc** [comment]
Ah I see. Cool, thanks for sharing all this context.

Yeah, for the reasons specified above, we're not going to add expansion of `~` any time soon, and generally recommend that people use directory structure relative to Tiltfile instead.

You might even add a local to do a directory structure check with some useful error messages, e.g.:

```
local('if [ ! -e "./README.md" ]; then echo "directory does not exist; please see directory structure at <wiki>" && false; fi')
```

Going to close this issue as `WONTFIX`, but let us know if you run into any more trouble with this.
