### ISSUE TITLE
helm() does not respect .tiltignore file

### ISSUE THREAD

**Issue by digger18** [windmilleng/tilt#2602]
I have a helm chart which has subcharts in it (using requirements.yaml).
In my .tiltignore file I added `*.tgz` and placed it next to my Tiltfile.
After I do `helm dep update` in the helm chart directory (which fetches the subcharts as .tgz files to charts/ directory), Tilt enters a restart loop because it detects (and not ignoring) the newly modified/added .tgz charts.

**Comment by nicks** [comment]
thanks for the report! let me poke at this a bit and see if i can figure out what's happening

**Comment by nicks** [comment]
OK, I double-checked, and I *think* Tilt is working correctly here.

To make sure that charts don't trigger rebuilds, you need to add this to your `.tiltignore`

```
**/*.tgz
**/charts
**/tmpcharts
```

.tiltignore works like .dockerignore, and doesn't match subdirectories by default.

I'm going to
- add a note in the Helm documentation on this, since I expect other people will want to copy this stanza, and
- make sure we have a second bug about detecting infinte reload

**Comment by nicks** [comment]
added a note on this to the helm guide:
https://docs.tilt.dev/helm.html

**Comment by KOGI** [comment]
Possible solution: #3404
