### ISSUE TITLE
Liveupdate 'sync' outside context

### ISSUE THREAD

**Issue by devcsrj** [windmilleng/tilt#2766]
According to the live update [sync section](https://docs.tilt.dev/live_update_reference.html#what-files-can-i-sync-how-are-builds-triggered):

> To put it another way: there’s no way for those files to get into the container in the first place, because they would never be included in the Docker build. (If this is functionality you need, let us know.)

So here is my case, to let you know! 👂 

I have a gradle project, which typically looks like:

```
.
├── build
│   ├── classes
│   ├── resources
├── build.gradle
└── src
```

If **sync outside context is allowed**, I could have configured this using:

```
custom_build(
   "image",
   "./gradlew dockerBuildImage -PdockerRef=$EXPECTED_REF",
    deps=[
        "src",
        "build.gradle"
    ]
    ...
)
```

But because **I can't**, I instead needed to setup `deps` to watch for the `build` directory, and then tell my IDE to compile/build just to update the `build/` dir.

**Comment by nicks** [comment]
Is your use-case similar to the one in https://github.com/windmilleng/tilt/issues/2765 ?

I'm not sure this would even work like you expect, since the sync() would only sync files that have changed, and assume files that have not changed are already in the container. I think the local_resource + sync() solution I proposed there will make you a lot happier (though we need better example projects on how people typically set this up)

**Comment by devcsrj** [comment]
Yes! `local_resource` did [the trick](https://github.com/windmilleng/tilt/issues/2765#issuecomment-573549308).
