### ISSUE TITLE
k3s support doesn't allow selecting local building

### ISSUE THREAD

**Issue by generalconsensus** [windmilleng/tilt#2767]
https://github.com/rancher/k3d/issues/19

Allows k3s to do local image building but tilt does not appear to support

**Comment by nicks** [comment]
Thanks for the request! You can currently do this now!

If you set up k3d with a registry as described in this doc (https://github.com/rancher/k3d/blob/master/docs/examples.md#connect-with-a-local-insecure-registry), then you can use the default_registry Tiltfile function (https://docs.tilt.dev/api.html#api.default_registry)

Your Tiltfile would look like

```
default_registry('registry.local:5000')
```

There are also some proposals to make this a bit more automatic, for details on those see https://github.com/windmilleng/tilt/issues/1620 (for auto-discovery of private registries) or https://github.com/windmilleng/tilt/issues/2001 (for using `k3d import-images`)

I'm going to close this feature request because it already overlaps a lot with the other ones filed, but feel free to comment if you have additional questions
