### ISSUE TITLE
cli interface for running tests on services and exiting with error

### ISSUE THREAD

**Issue by jazzdan** [windmilleng/tilt#2794]
From @Raffo in #tilt:

>I would love to use tilt to deploy an app and its dependencies to kubernetes and deploy a kubernetes job that contains some tests. I’d love to then wait for the job and exit with the result. I understand this sounds like CI, but I think unifying the same workflow that I can use to run e2e tests via kubernetes jobs on my pre-commit work AND what CI would be a huge win.

**Comment by nicks** [comment]
This came up again when we were talking to Jason May and Travis Cline yesterday.

I think they wanted the tests to be run with a local process rather than a k8s Job, tho I think any real solution to this problem would support either way to run the tests

You can kind of hack this workflow together with 
1) some k8s_yaml() calls
2) a local_resource that runs tests
3) Adding resource_deps so that the local_resource waits for the kubernetes services to come up
4) Starting tilt with --hud=false --watch=false

But the experience will have just enough gaps to feel broken. e.g., Tilt won't exit with the right status code. And the test will hang forever if the pods don't come up.

**Comment by nicks** [comment]
(also agree this is closely related to the CI discussion at https://github.com/windmilleng/tilt/issues/988, 
though i think this issue is a strict subset of what a good CI experience would look like)

**Comment by nicks** [comment]
Tilt v0.13.0 should have a `tilt ci` command that I think will help a lot with this

**Comment by nicks** [comment]
https://docs.tilt.dev/cli/tilt_ci.html
