### ISSUE TITLE
"tilt down" destroys a pre-existing namespace referenced by helm function

### ISSUE THREAD

**Issue by armsnyder** [windmilleng/tilt#2805]
This affects Tiltfiles with the `helm` function. When you run "tilt down", Tilt will destroy the Kubernetes namespace referenced in the `helm` function, **even if that namespace existed in the Kubernetes cluster before running "tilt up" initially**.

**Repro steps:**
1. Create a Helm chart named "foo" containing any one resource:
   ```yaml
   apiVersion: v1
   kind: Pod
   metadata:
     name: foo
   spec:
     containers:
       - name: alpine
         image: alpine
     restartPolicy: Never
   ```

1. Create a Tilefile:
   ```python
   k8s_yaml(helm('foo', namespace='bar'))
   ```

1. Create the namespace manually:
   ```bash
   $ kubectl create namespace bar
   ```

1. Run "tilt up"
   ```bash
   $ tilt up
   
   ● (Tiltfile) ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌
   HISTORY: EDITED FILES Tiltfile                
   ● foo ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌
   HISTORY: FIRST BUILD                          
   K8S POD: foo                                  
   ▼ ● uncategorized ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌
   (Kubernetes objects that don't match a group)
   bar:namespace
   ```

1. Run "tilt down"
   ```bash
   $ tilt down
   
   Beginning Tiltfile execution
   Running: [helm template /Users/asnyder/Documents/foo --generate-name --namespace bar]
   Successfully loaded Tiltfile (106.673875ms)
   Deleting via kubectl: Pod/foo
   
   Deleting via kubectl: Namespace/bar
   ```

**Expected behavior:** Tilt should not destroy a namespace that it did not itself create.

**Actual behavior:** Tilt will always destroy the namespace referenced in the `helm` function in the Tiltfile.

**Known Workaround:** It looks like the `helm()` function is prepending a Namespace resource to the output of `helm template`. That namespace can be stripped by modifying the Tilefile like so:

   ```python
   helm_template = str(helm('foo', namespace='bar'))
   helm_template = helm_template[helm_template.index('---'):]
   k8s_yaml(blob(helm_template))
   ```

**Comment by nicks** [comment]
Thanks for the report! Ya, this seems like a bug.

as an aside, @jazzdan - didn't Helm 3 remove the auto-create-namespace behavior in Helm 2?

**Comment by jazzdan** [comment]
@nicks that's correct

**Comment by jazzdan** [comment]
So I think the solutions here are a little nuanced and warrant some discussion upfront.

## The Problem

To be clear: the problem is that when Tilt is told to apply a namespace it automatically adds the Tilt "managed by" label. When this namespace is applied to a cluster that already has that namespace _without_ the "managed by" label, that namespace is modified to include the managed by label.

Then when `tilt down` is executed, Tilt deletes the namespace that it modified.

## What I just tried, and why it won't work

The solution I just tried, where `tilt down` only deletes resources that have the "managed by Tilt" label doesn't work because when `tilt up` is run it _modifies_ any existing namespaces to have that "managed by Tilt" label.

## Possible Solutions
1. Model the fact that we _might_ need to create a namespace differently in the data model. Instead of blindly including the namespace YAML, store in the state that we _might_ need to create the namespace, and have the engine check to see if the namespace exists before it tries to create it. If it does exist, don't do anything. It it doesn't exist, generate appropriate namespace YAML (with a "manged by Tilt" label) and apply it
2. Some sort of Tiltfile parmaeter where you can opt out of automatic namespace creation for the `helm` built-in. For example:

```python
helm('mychart', namespace='foo', create_namespace_automatically=False)
```

What do folks think?

**Comment by nicks** [comment]
Another possible option: change `tilt down` to leave namespaces intact by default. That's honestly the behavior I prefer when using `tilt down` day-to-day, and hacking it together is kind of a pain (see how we do it in the integration tests: https://github.com/windmilleng/tilt/blob/master/integration/Tiltfile)

I think this is all highly related to the general tension about Tilt Lifecycle (https://github.com/windmilleng/tilt/issues/1699) and the default behavior of `tilt down`
