### ISSUE TITLE
Return docker image information on docker_build

### ISSUE THREAD

**Issue by rpocase** [windmilleng/tilt#2880]
I have an eventual use case where I want to pass the docker_build image ID to other tooling (in my case, [argo](https://github.com/argoproj/argo/) workflows) from within tilt. Technically, I could do this using `k8s_yaml`, but I may want to start a workflow on demand or even stop the workflow midway through. 

I expect this could be done using use `custom_build(..., tag=mytag)`, but that is cumbersome for just wanting to retrieve one attribute of the build.

**Comment by nicks** [comment]
Re: argo workflows: is your idea that you'd have a local_resource that invokes the argo command-line, and picks things up from the docker_build? or something else?

We have a separate issue (https://github.com/windmilleng/tilt/issues/2839) where someone wants to add extra tags to their docker_build, so that they can use the jenkins build ID as a tag. Would that work for your use-case? Or do you specifically need the new tag that Tilt created and pushed?

**Comment by rpocase** [comment]
Yep, spot on. I have an argo workflow idea that would contain a step to run tests in cluster using an image built by tilt. I currently do this through a `local_resource` doing a `kubectl exec` into an existing pod just because it was faster for migration from docker-compose purposes. This could be migrated to a `Job`, but doesn't give as convenient options for step extension or stopping/pausing the job midway through (same problem with using `k8s_yaml` and telling Tilt about the `Workflow` CRD).

I think additional tags is sufficient for this use case. I would be all right closing this in favor of #2839

**Comment by maiamcc** [comment]
@rpocase alright, then I'll close this! If you wanna drop a note about your use case and the priority thereof in #2839, that would help us prioritize :)
