### ISSUE TITLE
sudo required for install script

### ISSUE THREAD

**Issue by base698** [windmilleng/tilt#3004]
Instead of `sudo` you chould create/use `~/.local/bin` and move the tilt exec there.  This is a standard pattern with some other tools.

**Comment by jazzdan** [comment]
Hey @base698, thanks for the suggestion!

I'm worried that if we implement this it will make installing Tilt more difficult since `~/.local/bin` is not in the standard $PATH on macOS or my Linux machine.

Maybe we check if `~/.local/bin` is in your $PATH. If it is, we install Tilt there. If it's not, we ask you if you'd like to give the script sudo access to install it to `/usr/local/bin`, or if you'd like to install it to `~/.local/bin` and add it to your $PATH.

What do you think?

**Comment by nicks** [comment]
You said there are other tools that use this pattern, could you link us to a couple? I'm curious how they deal with the PATH problems.

**Comment by base698** [comment]
I believe the aws cli toolkit does.  Deno: https://deno.land/x/install/install.sh does, but know that's far from standard.  Think the others are perhaps just things I've put there as I've taken to using it.

**Comment by base698** [comment]
@jazzdan I very much appreciate you making it easier.  I have been frustrated that skaffold requires kustomize when it's already available with kubectl.  We have migrated everything we are doing to tilt.  :)
