### ISSUE TITLE
restart_container() causing live updates to fail

### ISSUE THREAD

**Issue by marlowl** [windmilleng/tilt#3077]
I came across this error when experimenting with live updates:
```
Live Update failed with unexpected error:` ``ExecUpdater does not support `restart_container()` step. If you ran Tilt with `--updateMode=exec`, omit this flag. If you are using a non-Docker container runtime, see https://github.com/windmilleng/rerun-process-wrapper for a workaround`` `Falling back to a full image build + deploy
```
I was able to reproduce this behavior in a node example, snapshot: 
https://cloud.tilt.dev/snapshot/Aeqv5-YLbMiJCqmafqw=

Tiltfile:
```
k8s_yaml('deployment.yaml')
dm1_img_name = 'node-web-app'
docker_build(dm1_img_name, '.', dockerfile='Dockerfile',
  live_update=[
    sync('./server.js', '/usr/src/app/server.js'),
    run('npm start'),
    restart_container(),
  ]
)
```

`tilt doctor` result:

```
Tilt: v0.12.5, built 2020-02-27
System: linux-amd64
---
Docker
- Host: [default]
- Version: 1.40
- Builder: 2
---
Kubernetes
- Env: microk8s
- Context: microk8s
- Cluster Name: microk8s-cluster
- Namespace: default
- Container Runtime: containerd
- Version: v1.17.3
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
- User Mode: opt-out
- Machine: [redacted]
- Repo: [redacted]
```

**Comment by nicks** [comment]
Sorry about this! `restart_container()` does not work on microk8s. 

It might never work, because the microk8s container runtime doesn't support the necessary APIs.

The current workaround is to use something like https://github.com/windmilleng/rerun-process-wrapper, or use an app-specific tool to restart the server (like `nodemon`). We're working on better documentation on this.

At the very least, we should make the error message a bit better here.

**Comment by marlowl** [comment]
Good to know. Then I will use `nodemon` a bit more, that's not such a problem.
I think this issue can be closed then. Thanks for the answer! @nicks
