### ISSUE TITLE
Tiltifle should be able to specify min/max Tilt version

### ISSUE THREAD

**Issue by nicks** [windmilleng/tilt#3159]
As a devtools owner, I might want to declare my Tiltfile only compatible with particular versions of Tilt.

```
version_settings(min_version='0.10.0', max_version='0.11.0')
```

Tilt would error if its version string did not match what's in the Tiltfile, rather than failing cryptically.

We discussed this a bit when we first added version_settings in https://github.com/windmilleng/tilt/issues/2520. David at Unu has also asked L about this.

**Comment by nicks** [comment]
Note that this is independent of Tilt-cloud based version dashboard and promotion (https://github.com/windmilleng/tilt/issues/3125), which is more about soft nudge/promotion. This is more of a hard "This Tiltfile doesn't work with versions below X"

**Comment by drubin** [comment]
Interestingly for me is the `max_version='0.11.0'` because I believe that sadly you won't know if there are breaking changes when you add this in a git commit, and will never retroactively go back and fix them.

So maybe something more in line with Semver would be good.

like 
`version_settings(version='0.10.*')`
or 
`version_settings(version='^0.10.0')`
