### ISSUE TITLE
Allow ImagePullPolicy: Always on servers that you're not iterating on

### ISSUE THREAD

**Issue by victorwuky** [windmilleng/tilt#3209]
@maiamcc : Is ImagePullPolicy always set to PullIfNotPresent? 

This is from a discussion in #tilt

https://kubernetes.slack.com/archives/CESBL84MV/p1586939886185800

> are we setting imagePullPolicy to “PullIfNotPresent” irrespective of what k8 manifest is generated?

I see this commit: https://github.com/windmilleng/tilt/commit/79b37286f507364e007ef631aaa43edc8dca33e3#diff-a7deda2aacd55a59767f7ef8116b2af3R299

Maia: Is this intentional? If yes, could you please explain why? Also see that commit is a revert. So wanted to clarify.

**Comment by kavirajk** [comment]
Thanks @victorwuky I'm the one who started discussion on the slack.

It would be nice to have this control on the client side. Tilt changing the yaml manifest looks weird to me. 

Use case we have, is developers set the imagePullPolicy to Always to make sure always pull the "latest" artifacts by default.

**Comment by nicks** [comment]
Yep, this is intentional.

Setting `ImagePullPolicy: Always` means that whenever you make a change to your code, Kubernetes has to re-download all images.

That _might_ make sense when you're pushing to prod, but doesn't make sense in dev. You'd have to continuously re-download all the images every few seconds. This would make things much slower and less predictable (since an unrelated change could accidentally pull a new image).

**Comment by nicks** [comment]
(AFAIR, this is one of the very first things we added, in like the first couple weeks of building Tilt https://github.com/windmilleng/tilt/pull/124 because dev is way too slow without it)

**Comment by victorwuky** [comment]
@kavirajk : Does what Nick says make sense to you? Tilt is designed for a dev workflow where it reactively checks for changes you make whenever you say, change a line of code and hit save in your code editor. And so we don’t want to pull in a new image when that happens because it would be too slow. And instead possibly use live update to push those changes to your cluster immediately. https://docs.tilt.dev/live_update_tutorial.html

**Comment by victorwuky** [comment]
Closing this as being resolved. Kaviraj: Let us know if you have any other concerns/use cases we haven't considered.

**Comment by kavirajk** [comment]
Sorry for late response. @victorwuky @nicks  thanks for explaining :) 

I have following use case. may be you guys have some thoughts on it. 

We, in our company with 10 different teams using tils. Each team own some microservices. and we use Helm charts everywhere for all the services. each service's helm chart have specific "dev.values.yaml" by which we run on Tilt.

each team, makes changes only to their owned services. Other services should just start with whatever the latest version released by other team.

e.g: Team1 - service A, Team2 - Service B. and let's say Service A depens on Service B.

Team1 - on their local they build only serviceA with Live update (so any code changes are reflected). but service B is started with whatever the latest version the Team2 pushed recently.

To keep things simple, when every team releases, we also tag the service with `:dev` tag, (say `serviceB:dev`) - to denote the tip of the latest release of serviceB.

So that whoever need latest serviceB as dependency for their service, just add `image:serviceB:dev` and pullPolicy to `Always`.

This keeps service dependency across teams simple. 

IMPORTANT NOTE: We need PullPolicy Always only for dependent services(the services which the team never build local, just pull with "dev" tag)

If imagePullPolicy is hardcoded, this won't be possible. Every team needs to know the latest release version of every other services they depend on, Since each team releases more often even on a single day, this quick became unmanageable for us!

any thoughts? may be more elegant way other Tilt users solve this issue?. 

Thanks again in advance :)

**Comment by victorwuky** [comment]
Hi @kavirajk : Have you already read about Tiltfile configs?

- https://docs.tilt.dev/tiltfile_config.html
- https://blog.tilt.dev/2020/02/21/add-your-own-options-to-your-tilt-config.html

This should help you group services per team.

**Comment by nicks** [comment]
Hi @kavirajk ! Ya, I understand what you're getting at.

I think most of the teams that we work with try hard to avoid ":latest" tags that continuously update with the most recent version of a service (even if :latest is called :dev). The problem with this approach is that if you checkout an old build, it's hard to tell what version of the service will work with it.

But maybe there's away we could accommodate your specific use-case. For example, we could leave the ImagePullPolicy alone for services that you're not building locally. Let me investigate and get back to you

**Comment by nicks** [comment]
(updated the title to better reflect the use case)

**Comment by kavirajk** [comment]
thanks @nicks not editing k8s yaml when not building locally is exactly what I was looking for :) Thanks for taking this seriously! you guys are awesome! :) 

waiting for the release :)

**Comment by victorwuky** [comment]
@kavirajk you can now download the latest release which has the fix here: https://docs.tilt.dev/upgrade.html

**Comment by mateeyow** [comment]
I'm using multiple containers in one pud, is there a way to specify that this specific container should have imagePullPolicy to Always?

**Comment by nicks** [comment]
Hi @mateeyow ! Did you see my comment here? https://github.com/tilt-dev/tilt/issues/3209#issuecomment-614064746

If Tilt is managing an image build, it will override its own image pull policy (otherwise the image build won't work). If Tilt is not managing the image build, it will leave the image pull policy you set in the yaml. If that's different than the behavior you're seeing, or if you have a different use-case, please file a new issue with more context.
